apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-dpl
  labels:
    app: echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: jmalloc/echo-server:0.3.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-svc
spec:
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ing
spec:
  ingressClassName: nginx
  rules:
  - host: echo.localhost
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service: 
            name: echo-svc
            port: 
              number: 8080
